import { Location } from './internal-types';

export const Locations: Location[] = [
  {
    id: 799,
    city: 'גבעתיים',
    address: 'סירקין 17 ',
    description: 'לשכת רמת גן גבעתיים',
    name: 'לשכת רמת גן-גבעתיים',
  },
  {
    id: 802,
    city: 'תל אביב',
    address: 'מנחם בגין 125 ',
    description: 'לשכת תל אביב מרכז (קריית הממשלה)',
    name: 'לשכת תל אביב מרכז (קריית הממשלה)',
  },
  {
    id: 807,
    city: 'כפר סבא',
    address: 'ויצמן 140  ',
    description: 'לשכת כפר סבא',
    name: 'לשכת כפר סבא',
  },
  {
    id: 809,
    city: 'פתח תקוה',
    address: 'מוטה גור 4 מגדלי עופר',
    description: 'לשכת פתח תקוה',
    name: 'לשכת פתח תקוה',
  },
  {
    id: 816,
    city: 'חדרה',
    address: 'דוד שמעוני 42 ',
    description: 'לשכת חדרה',
    name: 'לשכת חדרה',
  },
  {
    id: 817,
    city: 'נתניה',
    address: 'דוד רמז 13 ',
    description: 'לשכת נתניה',
    name: 'לשכת נתניה',
  },
  {
    id: 818,
    city: 'רמלה',
    address: 'הרצל 91 ',
    description: 'לשכת רמלה',
    name: 'לשכת רמלה',
  },
  {
    id: 819,
    city: 'רחובות',
    address: 'מוטי קינד 10 ',
    description: 'לשכת רחובות',
    name: 'לשכת רחובות',
  },
  {
    id: 821,
    city: 'חולון',
    address: 'שדרות ירושלים 164 ',
    description: 'לשכת חולון',
    name: 'לשכת חולון',
  },
  {
    id: 822,
    city: 'ירושלים',
    address: 'שלומציון המלכה 1 ',
    description: 'לשכת ירושלים',
    name: 'לשכת ירושלים',
  },
  {
    id: 823,
    city: 'מודיעין',
    address: 'תלתן 1 ',
    description: 'לשכת מודיעין-מכבים-רעות (לתושבי העיר בלבד)',
    name: 'לשכת מודיעין-מכבים-רעות (לתושבי העיר בלבד)',
  },
  {
    id: 824,
    city: 'מבשרת ציון',
    address: 'חניון בית ספר הראל ',
    description: 'לשכת מבשרת ציון',
    name: 'לשכת מבשרת ציון',
  },
  {
    id: 825,
    city: 'ירושלים',
    address: 'אליהו קורן 25 ',
    description: 'לשכת ירושלים דרום- הר חומה',
    name: 'לשכת ירושלים דרום-הר חומה',
  },
  {
    id: 826,
    city: 'בני ברק',
    address: "דרך זאב ז'בוטינסקי 168 מגדלי שק",
    description: 'לשכת בני ברק',
    name: 'לשכת בני ברק',
  },
  {
    id: 827,
    city: 'תל אביב',
    address: 'סלמה 53 קומה 4',
    description: 'לשכת תל אביב דרום (יפו)',
    name: 'לשכת תל אביב דרום (יפו)',
  },
  {
    id: 828,
    city: 'ראש העין',
    address: 'שלום שבזי 29 ',
    description: 'לשכת ראש העין',
    name: 'לשכת ראש העין',
  },
  {
    id: 841,
    city: 'נתיבות',
    address: 'שדרות ירושלים 10 ',
    description: 'לשכת נתיבות',
    name: 'לשכת נתיבות',
  },
  {
    id: 842,
    city: 'באר שבע',
    address: 'התקווה 4 קריית הממשלה',
    description: 'לשכת באר שבע',
    name: 'לשכת באר שבע',
  },
  {
    id: 843,
    city: 'דימונה',
    address: 'בניין עיריית דימונה ',
    description: 'לשכת דימונה',
    name: 'לשכת דימונה',
  },
  {
    id: 849,
    city: 'רהט',
    address: 'עיריית רהט בניין העירייה',
    description: 'לשכת רהט',
    name: 'לשכת רהט',
  },
  {
    id: 852,
    city: 'עכו',
    address: 'שלום הגליל 1 ',
    description: 'לשכת עכו',
    name: 'לשכת עכו',
  },
  {
    id: 853,
    city: 'נהריה',
    address: 'אירית 2 קניון נהריה',
    description: 'לשכת נהריה',
    name: 'לשכת נהריה ',
  },
  {
    id: 854,
    city: 'אשדוד',
    address: 'דרך מנחם בגין 1 מרכז צימר',
    description: 'לשכת אשדוד',
    name: 'לשכת אשדוד',
  },
  {
    id: 855,
    city: 'אשקלון',
    address: 'ברל כצנלסון 9 ',
    description: 'לשכת אשקלון',
    name: 'לשכת אשקלון',
  },
  {
    id: 856,
    city: 'חיפה',
    address: 'שדרות פל ים 15 א  ',
    description: 'לשכת חיפה',
    name: 'לשכת חיפה',
  },
  {
    id: 858,
    city: 'עפולה',
    address: 'יהושע חנקין 1 ',
    description: 'לשכת עפולה',
    name: 'לשכת עפולה',
  },
  {
    id: 859,
    city: 'בית שמש',
    address: 'אבא נעמת 1 ',
    description: 'לשכת בית שמש',
    name: 'לשכת בית שמש',
  },
  {
    id: 860,
    city: 'טבריה',
    address: 'יהודה הלוי 1 מרכז ביג פאשן דנילוף',
    description: 'לשכת טבריה',
    name: 'לשכת טבריה',
  },
  {
    id: 861,
    city: 'נוף הגליל',
    address: 'מעלה יצחק 29 ',
    description: ' לשכת נוף הגליל (נצרת עילית)',
    name: ' לשכת נוף הגליל (נצרת עילית)',
  },
  {
    id: 866,
    city: 'צפת',
    address: 'וייצמן 4 ',
    description: 'לשכת צפת',
    name: 'לשכת צפת',
  },
  {
    id: 867,
    city: 'קרית שמונה',
    address: ' 37 הרצל ',
    description: 'לשכת קרית שמונה',
    name: 'לשכת קרית שמונה',
  },
  {
    id: 868,
    city: 'כרמיאל',
    address: 'החרושת 9 ',
    description: 'לשכת כרמיאל',
    name: 'לשכת כרמיאל',
  },
  {
    id: 869,
    city: 'ראשון לציון',
    address: 'ישראל גלילי 3 ',
    description: 'לשכת ראשון לציון',
    name: 'לשכת ראשון לציון',
  },
  {
    id: 871,
    city: 'הרצליה',
    address: 'הדר 2 ',
    description: 'לשכת הרצליה',
    name: 'לשכת הרצליה',
  },
  {
    id: 872,
    city: 'אילת',
    address: 'שדרות התמרים 2 ',
    description: 'לשכת אילת',
    name: 'לשכת אילת',
  },
  {
    id: 889,
    city: 'סחנין',
    address: "עיריית סח'נין ",
    description: "לשכת סח'נין",
    name: "לשכת סח'נין",
  },
  {
    id: 893,
    city: 'מעלה אדומים',
    address: 'דרך קדם 5 ',
    description: 'לשכת מעלה אדומים',
    name: 'לשכת מעלה אדומים ',
  },
  {
    id: 899,
    city: 'מודיעין עילית',
    address: 'חזון דוד ',
    description: 'לשכת מודיעין עילית',
    name: 'לשכת מודיעין עילית',
  },
  {
    id: 951,
    city: 'מעלות תרשיחא',
    address: 'בן גוריון 1 ',
    description: 'לשכת מעלות תרשיחא',
    name: 'לשכת מעלות תרשיחא',
  },
  {
    id: 978,
    city: 'קרית אתא',
    address: 'דרך חיפה 52 ',
    description: 'לשכת קריות (קניון שער הצפון)',
    name: 'לשכת קריות (קניון שער הצפון)',
  },
  {
    id: 979,
    city: 'טייבה',
    address: 'אלבלדיה ',
    description: 'לשכת טייבה',
    name: 'לשכת טייבה',
  },
  {
    id: 1019,
    city: 'ירושלים',
    address: ' מעבר קלנדיה ',
    description: 'לשכת קלנדיה  قلنديا',
    name: 'לשכת קלנדיה  قلنديا',
  },
  {
    id: 1037,
    city: 'יקנעם',
    address: 'התמר 2 ',
    description: 'לשכת יקנעם',
    name: 'לשכת יקנעם',
  },
  {
    id: 1038,
    city: 'אריאל',
    address: 'יהודה 5 ',
    description: 'לשכת אריאל',
    name: 'לשכת אריאל',
  },
  {
    id: 1071,
    city: 'שדרות',
    address: 'מנחם בגין 4 ',
    description: 'לשכת שדרות',
    name: 'לשכת שדרות',
  },
  {
    id: 1073,
    city: 'קרית גת',
    address: 'ככר פז 3 ',
    description: 'לשכת קרית גת',
    name: 'לשכת קרית גת',
  },
  {
    id: 1327,
    city: 'קצרין',
    address: 'מרכז מסחרי איתן ',
    description: 'לשכת קצרין',
    name: 'לשכת קצרין',
  },
  {
    id: 1599,
    city: 'ירושלים',
    address: ' 257 אלמדינה אל מנורה צור באהר',
    description: 'לשכת צור באהר صور باهر',
    name: 'לשכת צור באהר صور باهر',
  },
  {
    id: 1822,
    city: 'דיר אל אסד',
    address: "אל ג'בל מועצה מקומית דיר אל אסד",
    description: 'לשכת דיר אל אסד',
    name: 'לשכת דיר אל אסד',
  },
  {
    id: 2265,
    city: 'אום אל פחם',
    address: 'אל מדינה ',
    description: 'לשכת אום אל פחם',
    name: 'לשכת אום אל פחם',
  },
];
